apiVersion: v1
kind: Service
metadata:
  name: longlaugu-service
  namespace: longlaugu
spec:
  type: NodePort
  selector:
    app: longlaugu-discord-bot-pod
  ports:
  - port: 8443
    protocol: TCP
    targetPort: 8443
    nodePort: 30010